services:
  identity-service:
    image: identity-service:latest
    build: .
    restart: "no"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/identity-service?createDatabaseIfNotExist=true
      - server.port=8080
    ports:
      - "8085:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17.1
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: identity-service
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  newman:
    image: postman/newman
    volumes:
      - type: bind
        source: ./postman
        target: /etc/newman
    entrypoint: [
      "newman",
      "run",
      "identity-service-v1.0 smoke-tests.postman_collection.json",
      "-e",
      "http-identity-service-8080.postman_environment.json"
    ]
    depends_on:
      identity-service:
        condition: service_healthy

volumes:
  postgres_data: