name: CD pipeline

on: ["push"]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run smoke tests
        run: docker compose up --build --abort-on-container-exit --exit-code-from newman
